[project]
name = "ecommerce-data-warehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lucasberenger", email = "thegreatberenger@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
ecommerce-data-warehouse = "ecommerce_data_warehouse:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
